using Srm.Runtime.Evidence;
using Xunit;

namespace Srm.Runtime.Tests;

public class EvidenceQuarantineStoreTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), "srm-evidence-" + Guid.NewGuid());
    private readonly string _sourceDir = Path.Combine(Path.GetTempPath(), "srm-outbox-" + Guid.NewGuid());
    private readonly EvidenceQuarantineStore _sut;

    public EvidenceQuarantineStoreTests()
    {
        Directory.CreateDirectory(_root);
        Directory.CreateDirectory(_sourceDir);
        _sut = new EvidenceQuarantineStore(_root);
    }

    public void Dispose()
    {
        if (Directory.Exists(_root)) Directory.Delete(_root, true);
        if (Directory.Exists(_sourceDir)) Directory.Delete(_sourceDir, true);
    }

    [Fact]
    public void Quarantine_CopiesFilesAndRecordsManifest()
    {
        File.WriteAllText(Path.Combine(_sourceDir, "result.txt"), "generated by AI agent");

        var run = _sut.Quarantine("my-app", "run-001", _sourceDir);

        Assert.Equal(EvidenceState.Quarantined, run.State);
        Assert.Equal(1, run.FileCount);
        Assert.True(File.Exists(Path.Combine(_root, "my-app", "run-001", "files", "result.txt")));
        Assert.True(File.Exists(Path.Combine(_root, "my-app", "run-001", "manifest.json")));
    }

    [Fact]
    public void Quarantine_ExcludesSanitizerViolations()
    {
        File.WriteAllText(Path.Combine(_sourceDir, "ok.txt"), "fine");
        // `\\?\`プレフィックスでWindowsのCONデバイス解釈をバイパスし実ファイルとして作成する
        // （EvidenceSanitizerTests.Scan_ReservedDeviceName_ReturnsViolation参照）。
        File.WriteAllText(@"\\?\" + Path.Combine(_sourceDir, "CON.txt"), "reserved name");

        var run = _sut.Quarantine("my-app", "run-002", _sourceDir);

        Assert.Equal(1, run.FileCount);
        Assert.Single(run.Violations);
        Assert.True(File.Exists(Path.Combine(_root, "my-app", "run-002", "files", "ok.txt")));
        Assert.False(File.Exists(Path.Combine(_root, "my-app", "run-002", "files", "CON.txt")));
    }

    [Fact]
    public void List_ReturnsAllQuarantinedRunsForApp()
    {
        _sut.Quarantine("my-app", "run-a", _sourceDir);
        _sut.Quarantine("my-app", "run-b", _sourceDir);

        var runs = _sut.List("my-app");

        Assert.Equal(2, runs.Count);
    }

    [Fact]
    public void Show_UnknownRun_ReturnsNull()
    {
        Assert.Null(_sut.Show("my-app", "does-not-exist"));
    }

    [Fact]
    public void Promote_CopiesFilesToDestinationAndKeepsQuarantineCopy()
    {
        File.WriteAllText(Path.Combine(_sourceDir, "artifact.txt"), "payload");
        _sut.Quarantine("my-app", "run-promote", _sourceDir);
        var destDir = Path.Combine(_root, "promoted-dest");

        _sut.Promote("my-app", "run-promote", destDir);

        Assert.True(File.Exists(Path.Combine(destDir, "artifact.txt")));
        // 検疫側の控えはpromote後も残る（DC-013: copyでありmoveではない）
        Assert.True(File.Exists(Path.Combine(_root, "my-app", "run-promote", "files", "artifact.txt")));
        Assert.Equal(EvidenceState.Promoted, _sut.Show("my-app", "run-promote")!.State);
    }

    [Fact]
    public void Reject_MarksRunAsRejectedWithoutDeleting()
    {
        _sut.Quarantine("my-app", "run-reject", _sourceDir);

        _sut.Reject("my-app", "run-reject");

        var run = _sut.Show("my-app", "run-reject");
        Assert.NotNull(run);
        Assert.Equal(EvidenceState.Rejected, run!.State);
        Assert.True(Directory.Exists(Path.Combine(_root, "my-app", "run-reject")));
    }

    [Fact]
    public void Promote_UnknownRun_Throws()
    {
        Assert.Throws<InvalidOperationException>(() =>
            _sut.Promote("my-app", "nope", Path.Combine(_root, "dest")));
    }

    [Fact]
    public void PurgeExpired_RemovesOnlyOldQuarantinedRuns()
    {
        _sut.Quarantine("my-app", "run-fresh", _sourceDir);
        _sut.Quarantine("my-app", "run-old", _sourceDir);
        _sut.Quarantine("my-app", "run-promoted", _sourceDir);
        _sut.Promote("my-app", "run-promoted", Path.Combine(_root, "dest"));

        // run-old を保持期限切れ扱いにするため、検疫時刻を過去に書き換える
        var oldRun = _sut.Show("my-app", "run-old")!;
        oldRun.QuarantinedAt = DateTimeOffset.Now.AddDays(-10);
        _sut.SaveIndex(oldRun);

        var purged = _sut.PurgeExpired("my-app", retentionDays: 7);

        Assert.Equal(1, purged);
        Assert.Null(_sut.Show("my-app", "run-old"));
        Assert.NotNull(_sut.Show("my-app", "run-fresh"));
        // Promoted済みは保持期限の対象外
        Assert.NotNull(_sut.Show("my-app", "run-promoted"));
    }
}
